---
title: "Resume of Sze Pui"
---


$$ Tsang Sze Pui $$
$$ +1 (201) 496-7214            sallietsang@gmail.com $$
__PERSONAL DESCRIPTION__


- An optimistic student who would like to make contribution and devote to the betterment of the world
by taking advantages of my scientific knowledge


__EDUCATION__    

[City University of Hong Kong](https://www.cityu.edu.hk/)    2016-2020
[Columbia University](https://www.columbia.edu/)             2021-Present 


__Bachelor in Biology and Chemistry (BCH) with minor in Media Communication__

- CGPA ranking top 25% in class

- Attended to the courses Computer Science, Calculus and Applied Statistic

- Opened a Facebook page “Blood cycle for student hk” targeted on CityU students to
promote the importance of blood donation

__WORK AND INTERNSHIP EXPERIENCE__


__Student Summer Internship Programme, Hong Kong Police Force__ 07/2018 -08/2018

- Participated in a project called “Development of Image Processing Algorithm” to train
character recognition engine for the extraction and identification of serial number on
banknotes with the application of Java

-  Developed the procedure for image processing and banknote character extraction

-  Established two separate databases for testing and training of recognition engine system

-  Analyzed the accuracy and the performance of the new recognition engine system by
using different parameters

__RESEARCH EXPERIENCE__
__Department of Chemistry, City University of Hong Kong__    09/2019 - 5/2020


__Final Year Project__

-  Initiate and conduct in a research “Feeding Selectivity Between Nature and Synthetic
Microfibers in Marine Mussels”

- Design the experiment and apply SPSS to analyze the data via two-way ANOVA



__Department of Biomedical Science, City University of Hong Kong__   12/2018 - 01/2019
__Position: Lab researcher (part-time)__

- Participated in a science epidemiological research “Discovering Bacterial Profile on
CityU Campus”with an aim to identify the bacteria profile on campus and prevent the
outbreak of infectious diseases

-  Carried out environmental data collection , bacterial isolation and identification,
antimicrobial susceptibility testing etc



__EXTRA-CURRICULAR ACTIVITIES AND COMMUNITY SERVICE__

__Summer Exchange, College of Engineering, Peking University__    07/2019 - 08/2019
-  Engaged in the course “Artificial Organ Engineering”, GPA 3.8


__Summer Exchange, National University of Singapore(NUS)__ 05/2019

__City University of Hong Kong__    10/2016-12/2016

__Position: Vice President of Election Board of the 24th Biology and Chemistry Society__

- Conducted and supervised the election according to department constitution

- Coordinated the election events including propagation,student consultation and voting
procedure

-  Summarized the election results and submitted the financial and work report


__Ebenezer School & Home for Visually Impaired__  07/ 2016-09/2016

__Position: Volunteer__

-Read out book and notes to assist the blind preparing for their Braille examination

__SKILLS__

Language:

- Native in Cantonese, fluent in Mandarin

- TOEFL:106/120 , IELTS: 7.0

-Adobe suite and MS office suite - Advanced

- Java-Basic

- R- Basic


